Best_Game: FirstGame.o GameUtils.o
	g++ FirstGame.o GameUtils.o -o Best_Game

FirstGame.o: FirstGame.cpp
	g++ -c FirstGame.cpp

GameUtils.o: GameUtils.cpp
	g++ -c GameUtils.cpp

clean:
	rm *.o Best_Game